### ISSUE TITLE
什么时候使用DisposablePool

### ISSUE THREAD

**Issue by qingweiSun** [xuexiangjys/RxUtil2#1]
请问什么情况下要用DisposablePool.get().add进去吗，我看你的demo polling add进去了但是其他的方法没有用DisposablePool add,是因为这是demo是吗

**Comment by xuexiangjys** [comment]
DisposablePool是一个订阅池的管理，像polling、网络请求这种带有周期性、延迟性的操作符时，如果不在页面OnDestroy时注销订阅的话，很容易发生内存泄露。
